//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertSkydriveFiles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\"${permaLink}\" target=\"_blank\"><img title=\"${name}\" alt=\"${name}\" src=\"${" +
            "permaLink}\" /></a>")]
        public string photoInsertPattern {
            get {
                return ((string)(this["photoInsertPattern"]));
            }
            set {
                this["photoInsertPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[audio:${permaLink}|titles=${name}]")]
        public string audioInsertPattern {
            get {
                return ((string)(this["audioInsertPattern"]));
            }
            set {
                this["audioInsertPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool previewPhoto {
            get {
                return ((bool)(this["previewPhoto"]));
            }
            set {
                this["previewPhoto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crifan2003@hotmail.com")]
        public string liveId {
            get {
                return ((string)(this["liveId"]));
            }
            set {
                this["liveId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://skydrive.live.com/?cid=9a8b8bf501a38a36")]
        public string skydriveFolderUrl {
            get {
                return ((string)(this["skydriveFolderUrl"]));
            }
            set {
                this["skydriveFolderUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool insertFolder {
            get {
                return ((bool)(this["insertFolder"]));
            }
            set {
                this["insertFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool uploadAutoHandleFilename {
            get {
                return ((bool)(this["uploadAutoHandleFilename"]));
            }
            set {
                this["uploadAutoHandleFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool uploadOverwrite {
            get {
                return ((bool)(this["uploadOverwrite"]));
            }
            set {
                this["uploadOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isKeepLogin {
            get {
                return ((bool)(this["isKeepLogin"]));
            }
            set {
                this["isKeepLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string loginInfoStr {
            get {
                return ((string)(this["loginInfoStr"]));
            }
            set {
                this["loginInfoStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${permaLink}")]
        public string videoInsertPattern {
            get {
                return ((string)(this["videoInsertPattern"]));
            }
            set {
                this["videoInsertPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${permaLink}")]
        public string otherInsertPattern {
            get {
                return ((string)(this["otherInsertPattern"]));
            }
            set {
                this["otherInsertPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool openInNewWin {
            get {
                return ((bool)(this["openInNewWin"]));
            }
            set {
                this["openInNewWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string addSufPhoto {
            get {
                return ((string)(this["addSufPhoto"]));
            }
            set {
                this["addSufPhoto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string addSufAudio {
            get {
                return ((string)(this["addSufAudio"]));
            }
            set {
                this["addSufAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rmvb;mkv;f4v;xv;")]
        public string addSufVideo {
            get {
                return ((string)(this["addSufVideo"]));
            }
            set {
                this["addSufVideo"] = value;
            }
        }
    }
}
